apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: votingapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FloMko/argocd_workshop.git
    targetRevision: main
    path: helmfile_structure
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: flask
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true